name: autoencoder
input: coordinate
params: {
  encoder_layers: [24, 40, 2],
  options: {
    encoder: {
      activation: "tanh"
    },
    decoder: {
      activation: "tanh"
    },
    norm_in: {
    }
  }
}