name: gnncv
input: coordinate
params: {
  n_cvs: 1,
  cutoff: 10,
  atomic_number: [6, 7, 8],
  model_options: {
    n_out: 6,
    n_bases: 10,
    n_polynomials: 6,
    n_layers: 2,
    n_messages: 2,
    n_feedforwards: 2,
    n_scalars_node: 6,
    n_vectors_node: 2,
    n_scalars_edge: 6,
    drop_rate: 0.0,
    activation: 'Tanh',
  }
}