name: cvae
encoder:
  name: MLP
  layers: 4
  hidden_dim: [128, 128, 128, 128]
  input_dim: 200
  output_dim: 32
  init: xavier
decoder:
  name: MLP
  layers: 4
  hidden_dim: [128, 128, 128, 128]
  input_dim: 166
  output_dim: 66
  init: xavier
transform: internal_coordinates