# batch_size: 4096
batch_size: 8192
shuffle: True
epoch: 200
loss: MSE
# loss_scale: step
optimizer:
  name: Adam
  params: {
    lr: 1e-3
  }
scheduler:
  name: ExponentialLR
  params: {
    gamma: 0.99
  }
num_workers: 8
train: True