batch_size: 4096
shuffle: True
epoch: 100
loss: cvae
loss_recon_lambda: 1
optimizer:
  name: Adam
  params: {
    lr: 1e-4
  }
scheduler:
  name: ExponentialLR
  params: {
    gamma: 0.99
  }
num_workers: 8
train: True
eval_freq: 25