train: True
epoch: 200
loader:
  batch_size: 8192
  shuffle: True
  num_workers: 8
  test: False
loss:
  name: infonce
  n: 8
  similarity: cosine
  temperature: 1
  reduction: sum
  margin: 1e-12
optimizer:
  name: Adam
  params: {
    lr: 5e-5
  }
scheduler:
  name: CosineAnnealingLR
  params: {
    T_max: 200,
    eta_min: 1e-6
  }