train: True
epoch: 500
loader:
  batch_size: 4096
  shuffle: True
  num_workers: 8
  test: False
# loss:
#   name: triplet-torch
#   margin: 1
#   p: 2
#   eps: 1e-6
#   reduction: mean
#   temperature: 10
loss:
  name: ntxent
  lambda_pos: 30
  similarity: cosine
  temperature: 0.1
  reduction: mean
  margin: 1.0
optimizer:
  name: AdamW
  params: {
    lr: 1e-3
  }
scheduler:
  name: CosineAnnealingWarmupRestarts
  params: {
    first_cycle_steps: 500,
    cycle_mult: 1.0,
    max_lr: 1e-3,
    min_lr: 1e-5,
    warmup_steps: 20,
    gamma: 1.0,
    last_epoch: -1
  }