train: True
epoch: 400
loader:
  batch_size: 8192
  shuffle: True
  num_workers: 8
  test: False
loss:
  name: nce
  similarity: cosine
  temperature: 1
  reduction: sum
  margin: 1e-12
optimizer:
  name: Adam
  params: {
    lr: 1e-5
  }
scheduler:
  name: CosineAnnealingLR
  params: {
    T_max: 400,
    eta_min: 1e-8
  }