batch_size: 4096
shuffle: True
epoch: 200
loss: mse
optimizer:
  name: Adam
  params: {
    lr: 1e-3
  }
scheduler:
  name: ExponentialLR
  params: {
    gamma: 0.99
  }
num_workers: 8
train: True
eval_freq: 25