batch_size: 65536
shuffle: True
epoch: 100
scale: 1
step_scale: False
state_representation: difference
loss:
  name: mse+reg4
  reduction: mean
optimizer:
  name: Adam
  params: {
    lr: 1e-4
  }
scheduler:
  name: CosineAnnealingLR
  params: {
    T_max: 100,
    eta_min: 1e-6
  }
num_workers: 8
train: True
test: False
noise_scale: 1