batch_size: 2048
shuffle: True
epoch: 8
scale: 100.0
step_scale: False
state_representation: difference
repeat: False
loss:
  name: MSE+reg3
  reduction: mean
optimizer:
  name: Adam
  params: {
    lr: 1e-3
  }
scheduler:
  name: CosineAnnealingLR
  params: {
    T_max: 10,
    eta_min: 1e-5
  }
# scheduler:
#   name: ExponentialLR
#   params: {
#     gamma: 0.99
#   }
# scheduler:
#   name: ReduceLROnPlateau
#   params: {
#     gamma: 0.8,
#     milestones: [30, 80, 150]
#   }
# scheduler:
#   name: CosineAnnealingWarmRestarts
#   params: {
#     T_0: 10,
#     T_mult: 1,
#     eta_min: 1e-5
#   }
num_workers: 8
train: True
test: False
noise_scale: 0.04