# batch_size: 4096
batch_size: 8192
shuffle: True
epoch: 100
scale: 100.0
step_scale: False
loss:
  name: mse
  reduction: mean
optimizer:
  name: Adam
  params: {
    lr: 1e-4
  }
scheduler:
  name: CosineAnnealingLR
  params: {
    T_max: 100,
    eta_min: 1e-5
  }
num_workers: 8
train: True
test: False
noise_scale: 1