# batch_size: 4096
batch_size: 8192
shuffle: True
epoch: 200
scale: 100.0
loss:
  name: mse
  reduction: mean
optimizer:
  name: Adam
  params: {
    lr: 1e-3
  }
scheduler:
  name: CosineAnnealingLR
  params: {
    T_max: 200,
    eta_min: 1e-5
  }
num_workers: 8
train: True
test: False
noise_scale: 0.01