train: False
ckpt_file: deeplda-v1
batch_size: 8192
shuffle: True
epoch: 0
scale: 100.0
step_scale: False
repeat: True
state_representation: difference
loss:
  name: mse
  reduction: mean
optimizer:
  name: Adam
  params: {
    lr: 1e-4
  }
scheduler:
  name: CosineAnnealingLR
  params: {
    T_max: 200,
    eta_min: 1e-3
  }
num_workers: 8
test: False
noise_scale: 1