name: tps
molecule: alanine
start_state: c5
goal_state: c7ax
sample_num: 4
temperature: 300
save: True
time_horizon: 10
thp_cv_bound: 75
simulation:
  force_field: ["amber99sbildn.xml", "tip3p.xml"]
  platform: OpenCL
  precision: mixed
  temperature: 300
metrics:
- epd
- thp
- energy