evaluate: True
generate: True
name: tps
molecule: double-well
save: True
start_state: left
goal_state: right
sample_num: 8
temperature: 1200
time_horizon: 500
thp_cv_bound: 0.4
metrics:
- epd
- thp
- ram
# - energy