evaluate: True
name: tps
molecule: double-well
start_state: left
goal_state: right
sample_num: 16
temperature: 300
save: True
time_horizon: 200
thp_cv_bound: 0.75
metrics:
- epd
- thp
- ram
# - energy