evaluate: True
name: tps
molecule: alanine
start_state: c5
goal_state: c7ax-minimized
sample_num: 16
save: True
thp_cv_bound: 0.75
time_horizon: 500
simulation:
  steered: True
  k: 100
  force_type: cv-mlp
  friction: 0.001
  timestep: 1
  force_field: ["amber99sbildn.xml", "tip3p.xml"]
  temperature: 300
  platform: OpenCL
  precision: mixed
metrics:
  epd:
    use: True
  thp:
    use: True
  ram:
    use: True
  energy:
    use: True
  projection:
    use: True
    gridsize: 400
    cmap: viridis
    divide_plot: True
    cv_index: 0
    number_of_bins: 10