evaluate: True
generate: True
name: tps
molecule: alanine
start_state: c5
goal_state: c7ax
sample_num: 64
save: True
simulation:
  steered: True
  k: 5000
  time_horizon: 1000
  force_type: gnncvtica
  force_version: v2
  friction: 0.001
  timestep: 1
  force_field: ["amber99sbildn.xml", "tip3p.xml"]
  temperature: 300
  platform: OpenCL
  precision: mixed
  cv_min: 0.3032218813896179
  cv_max: 0.3126109540462494
metrics:
  epd:
    use: True
  thp:
    use: True
    cv_bound: 0.75
  ram:
    use: True
  energy:
    use: True
  projection:
    use: True
    version: simulation
    gridsize: 100
    cmap: viridis
    bound_use: True
    contour_plot: True
    cv_index: 0
    number_of_bins: 10
