evaluate: True
name: tps
molecule: chignolin
start_state: unfolded
goal_state: folded
sample_num: 8
temperature: 300
save: True
time_horizon: 1500
thp_cv_bound: 0.75
steered_simulation:
  k: 0
  friction: 0.001
  timestep: 1
  force_field: ["implicit/gbn2.xml"]
  platform: OpenCL
  precision: mixed
  temperature: 300
metrics:
- epd
- thp
- ram
# - energy