evaluate: True
name: tps
molecule: alanine
start_state: c5
goal_state: c7ax-minimized
sample_num: 16
save: True
thp_cv_bound: 0.75
time_horizon: 500
steered_simulation:
  k: 2000
  force_type: deeplda
  friction: 0.001
  timestep: 1
  force_field: ["amber99sbildn.xml", "tip3p.xml"]
  temperature: 300
  platform: OpenCL
  precision: mixed
metrics:
- epd
- thp
- ram
# - energy