evaluate: True
name: tps
molecule: alanine
start_state: c5
goal_state: c7ax
sample_num: 8
save: True
thp_cv_bound: 0.75
steered_simulation:
  k: 0
  friction: 0.001
  timestep: 1
  force_field: ["amber99sbildn.xml", "tip3p.xml"]
  time_horizon: 500
  temperature: 300
metrics:
- epd
- thp
- ram
# - energy